name = "OpenColor"
uuid = "6b18b4be-af96-4ba3-bd8c-96b4a98fe4ba"
authors = ["Jongsu Liam Kim <jongsukim8@gmail.com>"]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"

[compat]
julia = "1"
ColorTypes = "^0"
